# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Media Muse CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies (Ubuntu only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev
        
    - name: Install system dependencies (macOS only)
      if: runner.os == 'macOS'
      run: |
        brew install dbus
        brew install automake
        brew install libtool
        brew install pkg-config
        brew install cmake
        export LDFLAGS="-L/opt/homebrew/opt/dbus/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/dbus/include"
        export PKG_CONFIG_PATH="/opt/homebrew/opt/dbus/lib/pkgconfig"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyinstaller
        if [ "$RUNNER_OS" == "Linux" ]; then
          pip install -r requirements.txt
          pip install patchelf
        elif [ "$RUNNER_OS" == "macOS" ]; then
          grep -v "patchelf" requirements.txt > requirements_macos.txt
          pip install -r requirements_macos.txt
          pip install PyQt5==5.15.10 PyQt5-sip==12.13.0
          LDFLAGS="-L/opt/homebrew/opt/dbus/lib" CPPFLAGS="-I/opt/homebrew/opt/dbus/include" pip install dbus-python
        else
          pip install -r requirements.txt
          pip install PyQt5==5.15.10 PyQt5-sip==12.13.0
        fi
      shell: bash

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name=media_muse_${{ runner.os }} --add-data "src:src" src/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: media_muse-${{ runner.os }}-py${{ matrix.python-version }}
        path: dist/*

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        body: Automated release for commit ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
